language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pyqt5
  - pip install pytest-ipynb
  - pip install pandas
  - pip install --quiet .
  - pip install "jsonschema<3"
# command to run tests#
script:
  - py.test --no-qt
